import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync, existsSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import { stagePortableClient } from './portable-client.ts'

const roots: string[] = []
const revision = 'a'.repeat(40)

function fixture(): { root: string; destination: string } {
  const root = mkdtempSync(join(tmpdir(), 'dsh-client-package-test-'))
  roots.push(root)
  const files: Record<string, string> = {
    'LICENSE': 'license bytes\n',
    'THIRD_PARTY_NOTICES.md': 'third-party attribution\n',
    'packages/api/remotes/lib/types/client/portable.d.ts': 'export interface Api {}\n',
    'packages/client/ui-conversation/lib/portable.js': 'export const conversation = 1;\n',
    'packages/client/ui-conversation/lib/types/client/portable.d.ts': 'export interface Conversation {}\n',
    'packages/client/ui-chat/lib/portable.js': 'export const chat = 1;\n',
    'packages/client/ui-chat/lib/types/client/portable.d.ts': 'export interface Chat {}\n',
    'packages/api/remotes/lib/portable.js': 'export const generated = 1;\n',
    'packages/api/remotes/lib/client/portable.d.ts': 'export declare const generated = 1;\n',
  }
  const manifests = [
    ['packages/api/remotes', '@deepseek-ai/dsh-api-remotes'],
    ['vendor/cordis', '@deepseek-ai/cordis'],
    ['packages/client/ui-conversation', '@deepseek-ai/dsh-client-ui-conversation'],
    ['packages/client/ui-chat', '@deepseek-ai/dsh-client-ui-chat'],
    ['packages/util/brand', '@deepseek-ai/dsh-brand'],
    ['packages/typert/protocol', '@deepseek-ai/dsh-typert-protocol'],
    ['packages/util/values', '@deepseek-ai/dsh-util-values'],
  ]
  for (const [directory, name] of manifests) {
    files[`${directory}/package.json`] = JSON.stringify({
      name, version: '1.0.0', license: 'MIT', dependencies: { zod: '^4.4.3', '@standard-schema/spec': '^1.1.0', 'host-only': '1.0.0' },
    })
  }
  for (const [path, content] of Object.entries(files)) {
    mkdirSync(dirname(join(root, path)), { recursive: true })
    writeFileSync(join(root, path), content)
  }
  return { root, destination: join(root, 'distribution') }
}

afterEach(() => {
  for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true })
})

describe('portable Client package', () => {
  it('keeps generated bytes and shared identities without Host dependencies', () => {
    const { root, destination } = fixture()
    stagePortableClient(root, destination, revision)
    expect(readFileSync(join(destination, 'index.js'))).toEqual(readFileSync(join(root, 'packages/api/remotes/lib/portable.js')))
    expect(readFileSync(join(destination, 'index.d.ts'))).toEqual(readFileSync(join(root, 'packages/api/remotes/lib/client/portable.d.ts')))
    expect(JSON.parse(readFileSync(join(destination, 'package.json'), 'utf8'))).toMatchObject({
      name: '@deepseek-ai/dsh-api-remotes-client',
      dependencies: {
        '@deepseek-ai/dsh-brand': '1.0.0',
        '@deepseek-ai/dsh-typert-protocol': '1.0.0',
        '@deepseek-ai/dsh-util-values': '1.0.0',
        zod: '^4.4.3',
      },
      peerDependencies: { '@deepseek-ai/cordis': '1.0.0' },
      dshSource: { commit: revision, package: '@deepseek-ai/dsh-api-remotes', entry: './client/portable' },
    })
    expect(readFileSync(join(destination, 'package.json'), 'utf8')).not.toContain('host-only')
  })

  it('stages application artifacts with one declaration graph and explicit shared dependencies', () => {
    const { root, destination } = fixture()
    stagePortableClient(root, destination, revision, true)
    const manifest: unknown = JSON.parse(readFileSync(join(destination, 'package.json'), 'utf8'))
    expect(manifest).toMatchObject({ name: '@deepseek-ai/dsh-client', dependencies: { '@standard-schema/spec': '^1.1.0' },
      dshSource: { commit: revision, packages: ['@deepseek-ai/dsh-api-remotes', '@deepseek-ai/dsh-client-ui-conversation', '@deepseek-ai/dsh-client-ui-chat'] } })
    expect(readFileSync(join(destination, 'index.js'), 'utf8')).toBe("export * from './api.js';\nexport * from './conversation.js';\nexport * from './chat.js';\n")
    expect(readFileSync(join(destination, 'chat.js'))).toEqual(readFileSync(join(root, 'packages/client/ui-chat/lib/portable.js')))
    expect(readFileSync(join(destination, 'index.d.ts'), 'utf8')).toContain('./types/packages/client/ui-chat/lib/types/client/portable.js')
    expect(readFileSync(join(destination, 'THIRD_PARTY_NOTICES.md'), 'utf8')).toBe('third-party attribution\n')
    expect(readFileSync(join(destination, 'package.json'), 'utf8')).not.toContain('host-only')
  })

  it('removes acquired application staging on a declaration failure', () => {
    const { root, destination } = fixture()
    writeFileSync(join(root, 'packages/client/ui-chat/lib/types/client/portable.d.ts'), "export * from 'missing-dependency';")
    expect(() => stagePortableClient(root, destination, revision, true)).toThrow('unresolved module')
    expect(existsSync(destination)).toBe(false)
  })

  it('does not overwrite a directory owned by another caller', () => {
    const { root, destination } = fixture()
    mkdirSync(destination)
    writeFileSync(join(destination, 'package.json'), 'owned by another caller')
    expect(() => stagePortableClient(root, destination, revision)).toThrow()
    expect(readFileSync(join(destination, 'package.json'), 'utf8')).toBe('owned by another caller')
  })

  it('rejects absent build outputs without creating a partial distribution', () => {
    const { root, destination } = fixture()
    rmSync(join(root, 'packages/api/remotes/lib/client/portable.d.ts'))
    expect(() => stagePortableClient(root, destination, revision)).toThrow()
    expect(existsSync(destination)).toBe(false)
  })

  it.each([
    "import { createSnapshotStore } from '@deepseek-ai/dsh-client-store';",
    "export { value } from './missing-chunk.js';",
    "const load = () => import('node:fs');",
    "const load = () => require('node:fs');",
  ])('refuses an unpacked runtime dependency before publishing: %s', (runtime) => {
    const { root, destination } = fixture()
    writeFileSync(join(root, 'packages/api/remotes/lib/portable.js'), runtime)
    expect(() => stagePortableClient(root, destination, revision)).toThrow(/runtime import/u)
    expect(existsSync(destination)).toBe(false)
  })

  it('requires a full source identity before staging', () => {
    const { root, destination } = fixture()
    expect(() => stagePortableClient(root, destination, 'main')).toThrow('full source commit')
    expect(existsSync(destination)).toBe(false)
  })
})
